<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PaymentverificationController extends Controller
{
    public function verify(Request $request)
    {
        dd($request->all());
        $status = $request->q;
        
        if($status === 'su')
        {

            //dd($status); if it is success then their is su else fu
            $oid = $request->oid;
            $amt = $request ->amt;
            $refId = $request->refId;
            //dump($oid,$amt,$refId);
    
           //dd($refId);
            
            $url = "https://uat.esewa.com.np/epay/transrec";
    
            //get the data from database to make sure their is no sql injection or any other security issue 
            $data = [
                'amt'=> 100,
                'rid'=> $refId, //this is referemce unique code that is generated by esewa
                'pid'=> 'ghsdfsghdfsghdfjhsgdfjhsdgfjhdgfjhdgfjhdgfjhfgjhfg-bsdjfhb-fjskdfb',
                'scd'=> 'EPAYTEST'
            ];
    
                $curl = curl_init($url);
                curl_setopt($curl, CURLOPT_POST, true);
                curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
                curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
                $response = curl_exec($curl);
                curl_close($curl);
    
                //dd($response);
    
                if(strpos($response,"Success")){
                    dd('transaction successful');
                }else{
                    dd('transaction failed');
                }
        }else{
            dd('Transaction failed');
        }

    }

   
}
